# Site settings
title: Traansformation Design Studio

# SEO plugin
url: "http://traansformation.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# GA
google_analytics_ua: "UA-77671345-1"