# Site settings
title: Traansformation Design Studio | Vishwakarma, Vastu, Transformation, Interior, Interior Design, Design, Drafting, Designer, Designers, Interior Designers, Interior Designing, Traansformation, Transformation, Intricate, IIID, Thane, Borivali, Hira, Hiralal, Manjusha, Expertise, Experience, Turnkey, Turnkey Solutions, Turnkey Contract, Architects, Carpenters, Space Planning, Space Management, Interior Design Consultations

# SEO plugin
url: "http://traansformation.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# GA
google_analytics_ua: "UA-77671345-1"